### ISSUE TITLE
Uncaught TypeError: Cannot read property '56' of undefined

### ISSUE THREAD

**Issue by remikujawski** [joehoyle/atom-autocomplete-wordpress-hooks#21]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.0 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [autocomplete-wordpress-hooks](https://github.com/joehoyle/atom-autocomplete-wordpress-hooks) package 0.2.2

### Stack Trace

Uncaught TypeError: Cannot read property '56' of undefined

```
At /Users/remi.kujawski/.atom/packages/autocomplete-wordpress-hooks/lib/provider.js:111

TypeError: Cannot read property '56' of undefined
    at Object.isInFilter (/packages/autocomplete-wordpress-hooks/lib/provider.js:111:41)
    at Object.getSuggestions (/packages/autocomplete-wordpress-hooks/lib/provider.js:37:13)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:337:60
    at Array.forEach (native)
    at AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:313:23)
    at AutocompleteManager.findSuggestions (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:302:25)
```

### Commands

```
     -5:38.2.0 core:move-up (input.hidden-input)
  2x -4:38.7.0 core:close (input.hidden-input)
  2x -3:42.9.0 core:move-up (input.hidden-input)
     -3:42.2.0 editor:move-to-first-character-of-line (input.hidden-input)
     -3:38.8.0 core:move-down (input.hidden-input)
  2x -3:38 editor:move-to-end-of-word (input.hidden-input)
  3x -3:37.2.0 core:move-up (input.hidden-input)
     -3:36.3.0 core:move-down (input.hidden-input)
     -3:35.2.0 snippets:next-tab-stop (input.hidden-input)
     -3:35.2.0 snippets:expand (input.hidden-input)
     -3:35.2.0 editor:indent (input.hidden-input)
     -3:23.9.0 editor:newline (input.hidden-input)
     -0:33.4.0 autocomplete-plus:confirm (input.hidden-input)
     -0:33.4.0 snippets:expand (atom-text-editor.editor.is-focused)
  3x -0:32.4.0 core:move-right (input.hidden-input)
  3x -0:31.8.0 core:move-left (input.hidden-input)
```

### Non-Core Packages

```
acf-snippets 0.6.2 
advanced-custom-fields-snippets 1.1.0 
apex-syntax 0.1.0 
apex-ui 1.0.0 
atom-autocomplete-php 0.25.6 
atom-beautify 0.30.4 
atom-compile-less 0.12.0 
atom-dracula-black 0.3.0 
atom-less 0.1.10 
atom-mac-terminal 1.0.4 
atom-material-syntax 1.0.6 
atom-material-syntax-dark 1.0.0 
atom-material-syntax-light 0.4.6 
atom-material-ui 2.0.4 
atom-sass 0.4.0 
atom-uikit 1.2.2 
atom-wordpress 0.3.0 
autoclose-html 0.23.0 
autocomplete-wordpress-hooks 0.2.2 
dracula-syntax 2.0.5 
dracula-ui 0.6.0 
html-template-generator 0.3.0 
language-vue 0.23.1 
language-vue-component 0.5.0 
less-autocompile 1.0.0 
less-build 0.1.0 
less-compiler 0.6.2 
less-postcss-autocompile 1.2.3 
lesscompile 0.6.0 
php-cs-fixer 4.1.0 
pigments 0.40.1 
pinegrow-atom 0.3.1 
pure-syntax 0.3.0 
sass-autocompile 0.13.3 
tag 0.5.0 
uikit-atom 0.2.2 
vue-autocompile 0.0.6 
vue-autocomplete 0.1.1 
vue-format 0.4.0 
vue2-autocomplete 0.1.0-alpha.4 
wordpress 0.2.0 
wordpress-api 1.2.2 
wordpress-autocomplete 1.2.0 
wordpress-dictionary 4.4.0 
wordpress-go-function 0.1.0 
wordpress-suite 1.1.1 
wp-dev 0.3.5 
zp-acf-snippets 0.4.0 
```

**Comment by joehoyle** [comment]
Fixed in v0.2.3

**Comment by remikujawski** [comment]
No it isn’t!


Od: Joe Hoyle <notifications@github.com> <notifications@github.com>
Odpowiedz: joehoyle/atom-autocomplete-wordpress-hooks
<reply@reply.github.com>
<reply@reply.github.com>
Data: 22 sierpnia 2017 at 18:14:58
Do: joehoyle/atom-autocomplete-wordpress-hooks
<atom-autocomplete-wordpress-hooks@noreply.github.com>
<atom-autocomplete-wordpress-hooks@noreply.github.com>
DW: remikujawski <remi.kujawski@gmail.com> <remi.kujawski@gmail.com>, Author
<author@noreply.github.com> <author@noreply.github.com>
Temat:  Re: [joehoyle/atom-autocomplete-wordpress-hooks] Uncaught
TypeError: Cannot read property '56' of undefined (#21)

Closed #21
<https://github.com/joehoyle/atom-autocomplete-wordpress-hooks/issues/21>.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/joehoyle/atom-autocomplete-wordpress-hooks/issues/21#event-1216254794>,
or mute the thread

**Comment by joehoyle** [comment]
@remikujawski still the exact same error?

**Comment by remikujawski** [comment]
Ok - it is now - thx..


Od: Joe Hoyle <notifications@github.com> <notifications@github.com>
Odpowiedz: joehoyle/atom-autocomplete-wordpress-hooks
<reply@reply.github.com>
<reply@reply.github.com>
Data: 22 sierpnia 2017 at 19:41:46
Do: joehoyle/atom-autocomplete-wordpress-hooks
<atom-autocomplete-wordpress-hooks@noreply.github.com>
<atom-autocomplete-wordpress-hooks@noreply.github.com>
DW: remikujawski <remi.kujawski@gmail.com> <remi.kujawski@gmail.com>,
Mention <mention@noreply.github.com> <mention@noreply.github.com>
Temat:  Re: [joehoyle/atom-autocomplete-wordpress-hooks] Uncaught
TypeError: Cannot read property '56' of undefined (#21)

@remikujawski <https://github.com/remikujawski> still the exact same error>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/joehoyle/atom-autocomplete-wordpress-hooks/issues/21#issuecomment-324099894>,
or mute the thread
