### ISSUE TITLE
Double parenthesis on closing line

### ISSUE THREAD

**Issue by rmccue** [joehoyle/atom-autocomplete-wordpress-hooks#3]
Typing `add_action(` automatically adds the closing parenthesis afterwards. Autocompleting the function into place adds on a `} );` at the end (optionally with priority/arg number), which leads to a double up:

``` php
add_action( 'init', function() {

} );)
```

The following paren should be eaten by the autocompletion to avoid this.

**Comment by rmccue** [comment]
Still hitting into this @joehoyle

**Comment by joehoyle** [comment]
This will be fixed in 0.2.1
