### ISSUE TITLE
Closing brace has too much spacing

### ISSUE THREAD

**Issue by rmccue** [joehoyle/atom-autocomplete-wordpress-hooks#4]
Currently, the closing brace autocompletes to `} );`

Although there's no standard for this in WP's PHP, there is one for [WP JS](https://make.wordpress.org/core/handbook/best-practices/coding-standards/javascript/#arrays-and-function-calls), which is to _not_ space this out.

**Comment by joehoyle** [comment]
This is fixed in 0.2.1 which will be released shortly.
