### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by UVLabs** [joehoyle/atom-autocomplete-wordpress-hooks#5]
nothing happens... I even try doing what the gif is showing but nothing happens. I get no autocomplete options.

V0.2.0

atom v1.4.0

**Comment by joehoyle** [comment]
@UVLabs it's possible you have another autocomplete package which is taking precedance, could you try disabling all other packages that provide autocomplete to see if that changes things?

Thanks

**Comment by UVLabs** [comment]
apart from Atom core autocomplete packages I have no community autocomplete
packages,only community packages I have are:

Auto-indent (Not really auto, I still have to key it)
color-picker
emmet-simplified
file-icons
highlight-line
minimap
linter
liner-php

**Comment by onetrev** [comment]
I thought it wasn't working either. But the issue may be what I found.... you have to have best practice spacing, for example: 

`add_filter("post_thumb...")` will not bring up autocomplete... but with spacing after the open bracket, and you are gold! So like so:

`add_filter( "post_thumb..." )`

**Comment by joehoyle** [comment]
Added in 0.2.1 which will be released shortly.
