### ISSUE TITLE
Many hooks are missing like the_title, the_content and others

### ISSUE THREAD

**Issue by ramiy** [joehoyle/atom-autocomplete-wordpress-hooks#6]
How do you create the hooks.json ?

**Comment by maor** [comment]
Thanks for the useful plugin @joehoyle but I was wondering if you can share or open-source the method you used to generate `hooks.json` with.

**Comment by prasadnevase** [comment]
@ramiy - Yes, I tried it too with basic filter hook like the_content and action hook publish_post but they didn't show up in autocomplete. @joehoyle - Its really a great add on to Atom and would love if it covers all action+filter hooks :)

**Comment by joehoyle** [comment]
I just updated to version 0.2.2 which includes the missing hooks and filters. I'm now making use of the https://github.com/WordPress/phpdoc-parser to get all the hooks.
