### ISSUE TITLE
Issue with { charachter

### ISSUE THREAD

**Issue by n-for-all** [joehoyle/atom-autocomplete-wordpress-hooks#7]
Hello,

How can we remove the autocomplete for "{", because right now each time i write "{", it autocompletes with your hooks which is so annoying, it shouldn't, it should only display an autocomplete if { is preceded with " or '

https://www.dropbox.com/s/e4h7xtedga5f2p9/Screenshot%202016-09-26%2010.30.15.png?dl=0

Can we have a fix for this?

thanks

**Comment by joehoyle** [comment]
That's very odd, I do not get auto complete triggered. it seems like maybe this is happening with overlapping autocompletes or something with this I don't see any autocompletes: 

![](http://joehoyle-captured.s3.amazonaws.com/ficLSEGE.png)

**Comment by n-for-all** [comment]
Thanks, it seems there is a conflict between your plugin and wordpress api one, i disabled the other one and it worked.
