### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by DPUK44** [joehoyle/atom-autocomplete-wordpress-hooks#8]
I have Atom 1.12.7 and your plugin isn't working?

It's the only community plugin I have installed as all the others are core.

**Comment by AhmedShareef** [comment]
@dalepowell44  try [wordpress-dictionary](https://atom.io/packages/wordpress-dictionary) instead.

**Comment by DPUK44** [comment]
@AhmedShareef thank you so much man, great early Xmas present!

**Comment by joehoyle** [comment]
Close due to old - may have been fixed in v0.2.3
